@startuml Hello world

skinparam Style strictuml
skinparam SequenceMessageAlignment center
actor "Client1" as c
box "Сайт" #f9fabb
 		participant  "Site Front2" as sf
 		participant  "Site Back" as sb
box end
box "Портал" #E8ECFF
		actor        "Сотрудник портала" as sp
		participant  "Портал front" as pf
		participant  "Портал back" as pb
box end 

box "Службы"
		participant "Смежная служба" as ss
box end

== Создание обращения ==
c   ->  sf ++ : 1 Создать обращение
sf  ->  sb ++ : 2 Создать обращение
sb  ->  sb ++-- : 3 Сохранить\nобращение,\nсгенерировать\nrequestId
sb  ->  pb ++ : 4 Создать обращение (детали + requestId)
pb  ->  pb ++-- : 5 Сохранить обращение
alt #f0feed Обращение успешно сохранено
	sb <-- pb    : 6 Ответ(получено)
	sb  ->  sb ++-- : 7 Сохранить, что\nобращение\nсоздано в портале
else #fff0f5 Ошибка сохранения в портале
	sb <-- pb -- : 8 Ответ (ошибка)
	sb  ->  sb ++-- : 9 Проинформировать\nответственного\nоб ошибке
	sb  ->  sb ++-- : 10 Сохранить, что\nобращение НЕ\nсоздано в портале
end
sf <-- sb -- : 11 ответ(детали обращения)
c  <-- sf -- : 12 ответ(детали обращения)


== Обработка обращения ==

activate sp
sp  ->  pf ++ : 13 Получить все обращения
		   pf  ->  pb ++ : 14 Получить все обращения
		   pf <-- pb -- : 15 Ответ (все обращения)
sp <-- pf -- : 16 Ответ (все обращения)

sp  ->  pf ++ : 17 Открыть обращение
        pf  ->  pb ++ : 18 Получить детали обращения
        pf <-- pb -- : 19 Ответ (обращение)
sp <-- pf -- : 20 Ответ (обращение)

alt Нужна помощь смежной службы
sp  ->  pf ++ : 21 Открыть список смежных служб
		   pf  ->  pb ++ : 22 Получить список смежных служб
 	   pf <-- pb -- : 23 Ответ(список служб)
sp <-- pf -- : 24 Ответ(список служб)
 	
sp  ->  pf ++ : 25 Отправить смежной службе
 	   pf  ->  pb ++ : 26 Отправить смежной службе
 	   	       pb  ->  ss ++ : 27 Отправить обращение

 	   alt Обращение успешно получено
			       pb <-- ss    : 28 Ответ(получено)
			       pb  ->  pb ++-- : 29 Обновить статус
		   pf <-- pb    : 30 Ответ(обращение)
sp <-- pf    : 31 Ответ(обращение)	
		   else Ошибка отправки обращения
			       pb <-- ss -- : 32 Ответ(ошибка)
		   pf <-- pb -- : 33 Ответ(ошибка)
sp <-- pf -- : 34 Ответ(ошибка) 				
 	   end
 
else Обращение можно обработать
		alt Обращение спам
sp  ->  pf ++ : 35 Отметить как спам
		   pf  ->  pb ++ : 36 Отметить как спам
			       pb  ->  pb ++-- : 37 Обновить обращение
			       deactivate pb
		   deactivate pf
		else Можно ответить
sp  ->  pf ++ : 38 Ответить
		   pf  ->  pb ++ : 39 Ответить
			       pb  ->  pb ++-- : 40 Добавить ответ\nи обновить\nстатус
		end

		   sb  <-  pb ++ : 41 Обращение обработано (обновление + requestId)
		   sb  ->  sb ++-- : 42 Обновить обращение

		alt Обращение успешно обновлено
		   sb --> pb    : 43 Ответ(получено)
				   pb  ->  pb ++-- : 44 Сохранить, что\nизменения\nсинхронизированы
		   pf <-- pb    : 45 Ответ(обращение)
sp <-- pf    : 46 Ответ(обращение)
		else Ошибка обновления обращения
		   sb --> pb -- : 47 Ответ(ошибка)
					pb  ->  pb ++-- : 48 Сохранить, что\nизменения НЕ\nсинхронизированы
		   pf <-- pb -- : 49 Ответ(обращение + ошибка)
sp <-- pf -- : 50 Ответ(обращение + ошибка)
deactivate sp
		end
end

== Ответ от сторонней службы ==
ss  ->  pb ++: 51 Обращение обработано
pb  ->  pb ++--: 52 Обновить статус
ss <-- pb --: 53 Ответ(получено)

legend left 
'possible left | right | top | botton | center '
    ** Versions **
    <#Moccasin>|= Version |= Modified By |= Modified At 
    | v1 | Tatsiana | 20-12-2024
endlegend
@enduml