@startuml

[*] --> Черновик
Черновик --> Готов_к_согласованию: Проверить 
Готов_к_согласованию --> Согласован: Согласовать
Готов_к_согласованию -> На_доработке: Доработать
Готов_к_согласованию <- На_доработке: Проверить
Согласован --> Опубликован: Опубликовать
Опубликован --> Архив: Заархивировать
Архив --> [*]

Черновик --> Отменен
На_доработке -> Отменен
Отменен <-- Согласован
@enduml